[package]
name = "elementary_ca"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = { version = "3.0", features = ["termination"] }
termion = "1.5.6"

[[bin]]
name = "elementary-ca"
path = "src/bin/main.rs"
